config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  get '/search', to: 'searches#search'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  # validates :comment_content, presence: false, length: { minimum: 2 }
  validates :comment_content, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    # if @comment.save
    #   redirect_back(fallback_location: root_path)
    # else
    #   redirect_back(fallback_location: root_path)
    # end
    @comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    # @comment = Comment.find_by(book_id: params[:book_id], user_id: current_user.id)
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    # redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="m-1">
  <%= form_with(model:[book, comment], method: :book) do |f| %>
    <div class="form-group">
      <%= f.text_area :comment_content, size: "80x5" %>
    </div>
    <div class="form-group">
      <%= f.submit '送信' %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<% book.comments.each do |comment| %>
  <!--<div class="row">-->
  <tr>
    <td>
      <%= link_to user_path(comment.user) do %>
        <%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %><br>
        <%= comment.user.name %>
      <% end %>
    </td>
    <td><%= comment.comment_content %></td>
    <%if current_user == comment.user %>
      <!--<div class="bg-info">-->
      <td><%= link_to 'Destroy', book_comment_path(comment.book_id,comment.id), method: :delete, remote: true,  class: "btn btn-sm btn-danger"%></td>
      <!--</div>-->
    <% end %>
  </tr>
  <!--</div>-->
<% end %>

app/views/comments/create.js.erb
$("#<%= @comment.book_id.to_s %>").html("<%= j(render 'index', { book: @book }) %>")
$("textarea").val('')
$("#count").html("<%= @book.comments.count %>")

app/views/comments/destroy.js.erb
$("#<%= @comment.book_id.to_s %>").html("<%= j(render 'index', { book: @book }) %>")
$("#count").html("<%= @book.comments.count %>")